
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: app_development

  cable:
    <<: *default
    database: test_app_development_cable
    migrations_paths: db/cable_migrate
    username: test_app
    password: <%= ENV["TEST_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: test_app_test

production:
  primary: &primary_production
    <<: *default
    database: test_app_production
    username: test_app
    password: <%= ENV["TEST_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: test_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: test_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: test_app_production_cable
    migrations_paths: db/cable_migrate
